SET foreign_key_checks = 0;

delete from MB32.Annotation;
delete from MB32.AnnotationType;
delete from MB32.BaseObject;
delete from MB32.BasisOfRecord;
delete from MB32.CharacterState;
delete from MB32.Collection;
delete from MB32.CollectionObjects;
delete from MB32.ContinentOcean;
delete from MB32.Country;
delete from MB32.DeterminationAnnotation;
delete from MB32.DevelopmentalStage;
delete from MB32.ExternalLinkObject;
delete from MB32.ExternalLinkType;
delete from MB32.Form;
delete from MB32.Geolocated;
delete from MB32.Groups;
delete from MB32.History;
delete from MB32.Image;
delete from MB32.ImagingPreparationTechnique;
delete from MB32.ImagingTechnique;
delete from MB32.ITISCounter;
delete from MB32.Keywords;
delete from MB32.Kingdoms;
delete from MB32.Locality;
delete from MB32.Matrix;
delete from MB32.MatrixCell;
delete from MB32.MatrixCellValue;
delete from MB32.MbCharacter;
delete from MB32.MBTeam;
delete from MB32.MirrorInfo;
#delete from MB32.MissingImages;
delete from MB32.News;
delete from MB32.Otu;
delete from MB32.Publication;
#delete from MB32.RecentlyModified;
#delete from MB32.RecentlyModifiedTemp;
delete from MB32.sequence;
delete from MB32.ServerInfo;
delete from MB32.Sex;
delete from MB32.Spam;
delete from MB32.Specimen;
delete from MB32.SpecimenPart;
delete from MB32.synonym_links;
delete from MB32.Taxa;
#delete from MB32.Taxon;
delete from MB32.TaxonAuthors;
#delete from MB32.TaxonBranch;
#delete from MB32.TaxonBranchNode;
delete from MB32.TaxonConcept;
delete from MB32.TaxonomicUnits;
delete from MB32.TaxonUnitTypes;
delete from MB32.Tree;
delete from MB32.TypeStatus;
delete from MB32.`User`;
delete from MB32.UserGroup;
delete from MB32.UserGroupKey;
delete from MB32.UserProperty;
delete from MB32.Vernacular;
delete from MB32.`View`;
delete from MB32.ViewAngle;

insert into MB32.Annotation select * from  MB30.Annotation;
insert into MB32.AnnotationType select * from  MB30.AnnotationType;
insert into MB32.BaseObject select *,'www.morphbank.net',null from  MB30.BaseObject;
insert into MB32.BasisOfRecord select * from  MB30.BasisOfRecord;
insert into MB32.CharacterState select * from  MB30.CharacterState;
insert into MB32.Collection select * from  MB30.Collection;
insert into MB32.CollectionObjects select * from  MB30.CollectionObjects;
insert into MB32.ContinentOcean select * from  MB30.ContinentOcean;
insert into MB32.Country select * from  MB30.Country;
insert into MB32.CurrentIds select * from  MB30.CurrentIds;
insert into MB32.DeterminationAnnotation select * from  MB30.DeterminationAnnotation;
insert into MB32.DevelopmentalStage select * from  MB30.DevelopmentalStage;
insert into MB32.ExternalLinkObject select * from  MB30.ExternalLinkObject;
insert into MB32.ExternalLinkType select * from  MB30.ExternalLinkType;
insert into MB32.Form select * from  MB30.Form;
#insert into MB32.Geolocated select * from  MB30.Geolocated;
insert into MB32.Groups select * from  MB30.Groups;
insert into MB32.History select * from  MB30.History;
insert into MB32.Image select * from  MB30.Image;
insert into MB32.ImagingPreparationTechnique select * from  MB30.ImagingPreparationTechnique;
insert into MB32.ImagingTechnique select * from  MB30.ImagingTechnique;
insert into MB32.ITISCounter select * from  MB30.ITISCounter;
insert into MB32.Keywords(id, userId, groupId, objecttypeid, datetopublish,datecreated,keywords,submittedby,xmlKeywords,geolocated)
 select id, userId, groupId, objecttypeid, datetopublish,datecreated,keywords,submittedby,xmlKeywords,geolocated
 from  MB32.BaseObject;
insert into MB32.Kingdoms select * from  MB30.Kingdoms;
insert into MB32.Locality select * from  MB30.Locality;
insert into MB32.Matrix select * from  MB30.Matrix;
insert into MB32.MatrixCell select * from  MB30.MatrixCell;
insert into MB32.MatrixCellValue select * from  MB30.MatrixCellValue;
insert into MB32.MbCharacter select * from  MB30.MbCharacter;
insert into MB32.MBTeam select * from  MB30.MBTeam;
insert into MB32.MirrorInfo select * from  MB30.MirrorInfo;
#insert into MB32.MissingImages select * from  MB30.MissingImages;
insert into MB32.News select * from  MB30.News;
insert into MB32.Otu select * from  MB30.Otu;
insert into MB32.Publication select * from  MB30.Publication;
#insert into MB32.RecentlyModified select * from  MB30.RecentlyModified;
#insert into MB32.RecentlyModifiedTemp select * from  MB30.RecentlyModifiedTemp;
insert into MB32.sequence select * from  MB30.sequence;
insert into MB32.ServerInfo select * from  MB30.ServerInfo;
insert into MB32.Sex select * from  MB30.Sex;
insert into MB32.Spam select * from  MB30.Spam;
insert into MB32.Specimen select * from  MB30.Specimen;
insert into MB32.SpecimenPart select * from  MB30.SpecimenPart;
insert into MB32.synonym_links select * from  MB30.synonym_links ;
insert into MB32.Taxa select * from  MB30.Taxa;
#insert into MB32.Taxon select * from  MB30.;
insert into MB32.TaxonAuthors select * from  MB30.TaxonAuthors;
#insert into MB32.TaxonBranch select * from  MB30.TaxonBranch;
#insert into MB32.TaxonBranchNode select * from  MB30.TaxonBranchNode;
insert into MB32.TaxonConcept select * from  MB30.TaxonConcept;
insert into MB32.TaxonomicUnits select * from  MB30.TaxonomicUnits;
insert into MB32.TaxonUnitTypes select * from  MB30.TaxonUnitTypes;
insert into MB32.Tree select * from  MB30.Tree;
insert into MB32.TypeStatus select * from  MB30.TypeStatus;
insert into MB32.`User` select * from  MB30.`User`;
insert into MB32.UserGroup select * from  MB30.UserGroup;
insert into MB32.UserGroupKey select * from  MB30.UserGroupKey;
insert into MB32.UserProperty select * from  MB30.UserProperty;
insert into MB32.Vernacular select * from  MB30.Vernacular;
insert into MB32.`View` select * from  MB30.`View`;
insert into MB32.ViewAngle select * from  MB30.ViewAngle;
SET foreign_key_checks = 1;
repair table MB32.Keywords quick;
repair table MB32.Taxa quick;
