#!/usr/bin/php -q

<?php

require_once ('../configuration/image.server.php');
include_once('imageFunctions.php');

// Username and password
$db_user = 'webuser';
$db_passwd = 'namaste';
$host = 'localhost';
$port = '3306';
$database = 'MB27';


// Connect to MySQL server and Morphbank database.
if (!mysqli_connect("$host:$port" , "$db_user", "$db_passwd")){
    echo "Error, no database server.";
    exit;} 
else{
    $link = mysqli_connect("$host:$port" , "$db_user", "$db_passwd");

    if (!mysqli_select_db($link, $database)){
        echo "Error, no database Morphbank";
        exit;    } 
    else
        mysqli_select_db($link, $database);} 

// Parsing arguments
if ($argc == 2 ) { // one image
	main( $argv[1]);
} elseif ($argc == 3 ) { // range of images image
	$minImageId = intval($argv[1]);
	$maxImageId = intval($argv[2]);
	
	if (($minImageId>0) && ($maxImageId>0)) {
		for ($i=$minImageId;$i<=$maxImageId; $i++)
			main($i);
	}
} else {
	echo "\n
	========================================================
	Usage: ./createThumbs <Min image id> [Max image id]\n
	========================================================";
}

function main ( $imgId) {

	echo "\n================ Image: $imgId ====================\n";
	if ($imgRecord = getRecord ($imgId, "Image")) {
		
		// Converting images
		global $config;
		
		$imagePath = getImagePath($imgId);
		$imgSrc = $config->image->path->tiff.$imagePath.".tif";
		$imgsFileName[0] = $config->image->path->thumbs.$imagePath;	
		$imgsFileExt[0] = "jpg";

		$command = "convert -strip -resize 93x $imgSrc $imgsFileName[0].$imgsFileExt[0]";
		echo "$command\n";
		exec($command);	
	}
	echo "=================== End =========================\n";
}

function getRecord ($id, $table) {
	$sql = "SELECT * FROM $table Where id='$id'";
	//echo "$sql\n";
	$result = mysqli_query($link, $sql);
	
	if ($result && (mysqli_num_rows($result)==1)) {
		echo "$sql\n";
		return mysqli_fetch_array($result);
	} else {
		echo "Error:".mysqli_error($link);
		return false;
	}
}

?>

